apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-agent
subjects:
  - kind: ServiceAccount
    name: observability-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: observability-agent
  apiGroup: rbac.authorization.k8s.io
