apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-agent
  namespace: default
  labels:
    app: observability-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observability-agent
  template:
    metadata:
      labels:
        app: observability-agent
    spec:
      serviceAccountName: observability-agent
      containers:
        - name: agent
          image: anuragmishra22/observability-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WATCH_NAMESPACE
              value: "dev" # Empty = all namespaces
            - name: LABEL_SELECTOR
              value: "" # Optional: e.g. "app=myapp"
