apiVersion: v1
kind: Pod
metadata:
  name: observability-agent
  namespace: default
spec:
  serviceAccountName: observability-agent
  containers:
    - name: agent
      image: anuragmishra22/observability-agent:latest
      imagePullPolicy: Always
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      ports:
        - containerPort: 8080
