apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observability-agent
  namespace: default
subjects:
  - kind: ServiceAccount
    name: observability-agent
    namespace: default
roleRef:
  kind: Role
  name: observability-agent
  apiGroup: rbac.authorization.k8s.io
