apiVersion: v1
kind: Service
metadata:
  name: observability-agent
  namespace: default
spec:
  selector:
    app: observability-agent
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
